services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
