### Create user
POST http://localhost:3000/api/v1/users 
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john_doe@gmail.com",
    "password": "Hammad78612&"
}

### Get user by ID
GET http://localhost:3000/api/v1/users/1